import numpy as np
from recurrent.sequential import SequentialModel
from recurrent.rnn import RNNLayer
from recurrent.dense import Dense as OutputLayer
from recurrent.gru import GRU
from recurrent.lstm import LSTMLayer

# ! this shitty code is completely generated by AI

def get_memory_batch(batch_size, seq_len, vocab_size):
    """
    Returns:
    - x: (batch_size, seq_len, vocab_size) one-hot encoded
    - y: (batch_size,) the class to remember (0 or 1)
    """
    # 0 and 1 are triggers. 2 to vocab_size-1 are noise.
    noise = np.random.randint(2, vocab_size, (batch_size, seq_len))
    
    # Secret to remember: 0 or 1
    secrets = np.random.randint(0, 2, (batch_size,))
    
    # Put secret at the very beginning
    noise[:, 0] = secrets
    
    # One-hot encode inputs
    x = np.eye(vocab_size)[noise]
    return x, secrets

# --- 2. The Completed Training Loop ---
def run_memory_test(model, seq_len, vocab_size, iterations=400):
    """Trains the model to remember a bit over L steps."""
    for i in range(iterations):
        x_batch, y_batch = get_memory_batch(1, seq_len, vocab_size)
        target = y_batch[0]
        
        # 1. Forward pass
        # FIX: Bypass SequentialModel and call the recurrent layer directly 
        # so we get (seq_len, hidden_size) instead of the final logits.
        hidden_seq = model.layers[0].forward(x_batch[0]) 
        
        # 2. Prediction (Many-to-One)
        logits = model.output_layer.forward(hidden_seq[-1:]) # Shape: (1, vocab_size)
        probs = softmax(logits)
        
        # 3. Calculate Gradient for the Output Layer
        d_logits = probs.copy()
        d_logits[0, target] -= 1
        
        # 4. Backward Pass through Output Layer
        d_last_h = model.output_layer.backward(d_logits)
        
        # 5. Many-to-One Gradient Assembly
        dh_seq = np.zeros_like(hidden_seq)
        dh_seq[-1] = d_last_h 
        
        # 6. Backpropagate Through Time (BPTT) and Update
        model.layers[0].backward(dh_seq)
        model.optimizer.step()
        
    # --- Check Accuracy ---
    test_x, test_y = get_memory_batch(50, seq_len, vocab_size)
    correct = 0
    for j in range(50):
        # FIX: Use layers[0] here as well
        h = model.layers[0].forward(test_x[j])
        p = softmax(model.output_layer.forward(h[-1:]))
        if np.argmax(p) == test_y[j]: 
            correct += 1
    
    return correct / 50

# --- 1. Helper for Loss and Softmax ---
def softmax(x):
    # Stabilized softmax to prevent overflow
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / np.sum(e_x, axis=-1, keepdims=True)

def cross_entropy_loss(probs, target_idx):
    # probs: (1, vocab_size), target_idx: integer
    # Returns scalar loss
    return -np.log(probs[0, target_idx] + 1e-12)

lstm_h = 64
gru_h = 74
rnn_h = 128 

lr=0.01

# --- 3. Execute Experiment ---
vocab_size = 10
lengths = [10, 20, 50, 100, 200]
horizon_results = {"RNN": [], "GRU": [], "LSTM": []}

for L in lengths:
    print(f"\n--- Testing Memory Horizon: {L} steps ---")
    
    # Fresh initialization for each length test
    rnn_model = SequentialModel([RNNLayer(vocab_size, rnn_h)], OutputLayer(rnn_h, vocab_size), lr=lr)
    gru_model = SequentialModel([GRU(vocab_size, gru_h)], OutputLayer(gru_h, vocab_size), lr=lr)
    lstm_model = SequentialModel([LSTMLayer(vocab_size, lstm_h)], OutputLayer(lstm_h, vocab_size), lr=lr)

    for name, m in [("RNN", rnn_model), ("GRU", gru_model), ("LSTM", lstm_model)]:
        accuracy = run_memory_test(m, L, vocab_size)
        horizon_results[name].append(accuracy)
        print(f"{name} Accuracy: {accuracy*100:.1f}%")